[package]
name = "draw"
version = "0.1.0"
authors = ["lislis <mail@lislis.de>"]

[[bin]]
name = "image"
path = "src/main.rs"


[dependencies]
piston_window = "0.64.0"
find_folder = "0.3.0"
rand = "0.3.14"
